### ISSUE TITLE
How to guide: Translation using Lokalise

### ISSUE THREAD

**Issue by pkundu** [avniproject/avni-documentation#28]
https://docs.google.com/document/d/1jA2dcfQhENge3qN-QEMT9fNYrPz14qHRSgBVGG9mkmg/edit#heading=h.gmf62jb0k1mq

### AC:
- Add it under `End user guide`
- We can merge the new changes with the existing guide to prevent multiple documentations: https://avni.readme.io/docs/translation-management#4-uploading-translations - or delete the old one if everything is covered in the new one
- One thing that can be added is that: When orgs dont want Locations to be part of translations, then they need to bundle export without locations, import and export translations. This was required for Goonj since they had too many locations and hence was in need to translate other things before locations.
- Readme guidelines: https://avni.readme.io/docs/readme-guidelines Adhere to it wherever applicable

**Comment by mahalakshme** [comment]
Everything looks fine, Just having two inputs incase not thought of:
1. We can merge the new changes with the existing guide to prevent multiple documentations: https://avni.readme.io/docs/translation-management#4-uploading-translations
2. One thing that can be added is that: When orgs dont want Locations to be part of translations, then they need to bundle export without locations, import and export translations. This was required for Goonj since they had too many locations and hence was in need to translate other things before locations.

**Comment by mahalakshme** [comment]
@Parth7223 have added the comments from the ticket: https://avni.freshdesk.com/a/tickets/3929 above

**Comment by mahalakshme** [comment]
@pkundu this is done.
